name: Naukri Daily Automation

on:
  schedule:
    # ~4:21 AM IST
    - cron: '51 22 * * *'
    # ~6:15 AM IST
    - cron: '45 0 * * *'
    # ~10:14 AM IST
    - cron: '44 4 * * *'
    # ~12:00 PM IST
    - cron: '30 6 * * *'
    # ~3:26 PM IST
    - cron: '56 9 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install dependencies
        run: pip install selenium google-generativeai

      - name: Run Apply Script
        env:
          NAUKRI_USER: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASSWORD }}
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python apply_jobs.py
